// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://birzemvtbhhlosnizfbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcnplbXZ0YmhobG9zbml6ZmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mjc3MTgsImV4cCI6MjA3MDMwMzcxOH0.j2lrY_xY14dCcGXG-Z-FbMwOGoRYCI30hYhej-3mo20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});